### ISSUE TITLE
wrong number of arguments (0 for 1) on %= render_breadcrumbs.

### ISSUE THREAD

**Issue by skunkworker** [weppos/breadcrumbs_on_rails#55] opened 2014-01-30 10:20 UTC
I just barely installed render_breadcrumbs on Rails 3.2.15 & Ruby 2.1.0 and I cant seem to get around this error.
In a view
```
<%= render_breadcrumbs %>
```
throws a "wrong number of arguments (0 for 1)", error. Googling it I have been unable to find anyone with the same problems. Is there something that I am doing wrong?

**Comment by quockhanhbui** [comment] 2015-09-18 03:35
The same issue. But i fixed it. The reason is gems conflict.
In my case: 
```ruby
gem `twitter-bootstrap3-rails` 
# conflict with 
gem 'breadcrumbs_on_rails'.
```
When i removed gem `twitter-bootstrap3-rails`. The error went!

**Comment by weppos** [comment] 2016-08-07 11:44
Potentially duplicate of #65

**Closed by weppos** 2016-08-07 11:44 UTC
